# Generated by Django 5.2 on 2025-04-29 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('short_name', models.CharField(max_length=10, verbose_name='Сокращенное наименование')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тип документа',
                'verbose_name_plural': 'Типы документов',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='EconomicObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Экономический объект',
                'verbose_name_plural': 'Экономические объекты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('full_name', models.CharField(max_length=500, verbose_name='Полное наименование')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=9, verbose_name='КПП')),
                ('ogrn', models.CharField(max_length=15, verbose_name='ОГРН')),
                ('okpo', models.CharField(max_length=10, verbose_name='Код ОКПО')),
                ('okved', models.CharField(max_length=20, verbose_name='Код ОКВЭД')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('director_position', models.CharField(max_length=100, verbose_name='Должность руководителя')),
                ('director_name', models.CharField(max_length=255, verbose_name='ФИО руководителя')),
                ('accountant_name', models.CharField(max_length=255, verbose_name='ФИО бухгалтера')),
                ('stamp', models.ImageField(blank=True, null=True, upload_to='organization_stamps/', verbose_name='Печать')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='organization_signatures/', verbose_name='Подпись')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SellerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Статус продавца',
                'verbose_name_plural': 'Статусы продавцов',
            },
        ),
        migrations.CreateModel(
            name='VatRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ставка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Ставка НДС',
                'verbose_name_plural': 'Ставки НДС',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DocumentUPD',
            fields=[
                ('basedocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents_сreating.basedocument')),
                ('invoice_number', models.CharField(max_length=50, verbose_name='Номер счет-фактуры')),
                ('invoice_date', models.DateField(verbose_name='Дата счет-фактуры')),
                ('correction_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер исправления')),
                ('correction_date', models.DateField(blank=True, null=True, verbose_name='Дата исправления')),
                ('is_advance', models.BooleanField(default=False, verbose_name='Авансовый платеж')),
                ('seller_name', models.CharField(max_length=255, verbose_name='Наименование продавца')),
                ('seller_full_name', models.CharField(max_length=500, verbose_name='Полное наименование продавца')),
                ('seller_inn', models.CharField(max_length=12, verbose_name='ИНН продавца')),
                ('seller_kpp', models.CharField(max_length=9, verbose_name='КПП продавца')),
                ('seller_address', models.TextField(verbose_name='Адрес продавца')),
                ('seller_director_position', models.CharField(max_length=100, verbose_name='Должность руководителя')),
                ('seller_director_name', models.CharField(max_length=255, verbose_name='ФИО руководителя')),
                ('seller_accountant_name', models.CharField(max_length=255, verbose_name='ФИО бухгалтера')),
                ('consignor_name', models.CharField(max_length=255, verbose_name='Наименование грузоотправителя')),
                ('consignor_inn', models.CharField(max_length=12, verbose_name='ИНН грузоотправителя')),
                ('consignor_kpp', models.CharField(max_length=9, verbose_name='КПП грузоотправителя')),
                ('consignor_address', models.TextField(verbose_name='Адрес грузоотправителя')),
                ('consignor_director_name', models.CharField(max_length=255, verbose_name='ФИО руководителя')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Наименование клиента')),
                ('customer_inn', models.CharField(max_length=12, verbose_name='ИНН клиента')),
                ('customer_kpp', models.CharField(max_length=9, verbose_name='КПП клиента')),
                ('customer_address', models.TextField(verbose_name='Адрес клиента')),
                ('customer_director_position', models.CharField(max_length=100, verbose_name='Должность руководителя')),
                ('customer_director_name', models.CharField(max_length=255, verbose_name='ФИО руководителя')),
                ('consignee_name', models.CharField(max_length=255, verbose_name='Наименование грузополучателя')),
                ('consignee_inn', models.CharField(max_length=12, verbose_name='ИНН грузополучателя')),
                ('consignee_kpp', models.CharField(max_length=9, verbose_name='КПП грузополучателя')),
                ('consignee_address', models.TextField(verbose_name='Адрес грузополучателя')),
                ('consignee_director_name', models.CharField(max_length=255, verbose_name='ФИО руководителя')),
                ('contract_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Идентификатор гос. контракта')),
                ('print_form', models.CharField(max_length=255, verbose_name='Печатная форма')),
                ('transfer_basis', models.TextField(verbose_name='Основание передачи/получения')),
                ('transport_info', models.TextField(verbose_name='Данные о транспортировке и грузе')),
                ('transfer_position', models.CharField(max_length=100, verbose_name='Должность передатчика')),
                ('transfer_name', models.CharField(max_length=255, verbose_name='ФИО передатчика')),
                ('transfer_date', models.DateField(verbose_name='Дата отгрузки')),
                ('transfer_additional_info', models.TextField(verbose_name='Иные сведения об перемещении')),
                ('transfer_responsible_position', models.CharField(max_length=100, verbose_name='Должность ответственного за перемещение')),
                ('transfer_responsible_name', models.CharField(max_length=255, verbose_name='ФИО ответственного за перемещение')),
                ('receiver_position', models.CharField(max_length=100, verbose_name='Должность получателя')),
                ('receiver_name', models.CharField(max_length=255, verbose_name='ФИО получателя')),
                ('receipt_date', models.DateField(verbose_name='Дата получения (приемки)')),
                ('receipt_additional_info', models.TextField(verbose_name='Иные сведения о получении, приемке')),
                ('receipt_responsible_position', models.CharField(max_length=100, verbose_name='Должность ответственного за приемку')),
                ('receipt_responsible_name', models.CharField(max_length=255, verbose_name='ФИО ответственного за приемку')),
                ('document_seller_name', models.CharField(max_length=255, verbose_name='Наименование продавца-составителя')),
                ('document_seller_inn', models.CharField(max_length=12, verbose_name='ИНН продавца-составителя')),
                ('document_seller_kpp', models.CharField(max_length=9, verbose_name='КПП продавца-составителя')),
                ('document_customer_name', models.CharField(max_length=255, verbose_name='Наименование покупателя-составителя')),
                ('document_customer_inn', models.CharField(max_length=12, verbose_name='ИНН покупателя-составителя')),
                ('document_customer_kpp', models.CharField(max_length=9, verbose_name='КПП покупателя-составителя')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents_сreating.currency', verbose_name='Валюта')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents_сreating.documenttype', verbose_name='Тип документа')),
                ('seller_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_status', to='documents_сreating.sellerstatus', verbose_name='Статус продавца')),
                ('vat_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents_сreating.vatrate', verbose_name='Ставка НДС')),
            ],
            options={
                'verbose_name': 'УПД',
                'verbose_name_plural': 'УПД',
            },
            bases=('documents_сreating.basedocument',),
        ),
        migrations.CreateModel(
            name='ShipmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование документа')),
                ('number', models.CharField(max_length=50, verbose_name='Номер документа')),
                ('date', models.DateField(verbose_name='Дата документа')),
                ('upd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_docs', to='documents_сreating.documentupd', verbose_name='УПД')),
            ],
            options={
                'verbose_name': 'Документ об отгрузке',
                'verbose_name_plural': 'Документы об отгрузке',
            },
        ),
        migrations.CreateModel(
            name='PaymentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Номер документа')),
                ('date', models.DateField(verbose_name='Дата документа')),
                ('upd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_docs', to='documents_сreating.documentupd', verbose_name='УПД')),
            ],
            options={
                'verbose_name': 'Платежно-расчетный документ',
                'verbose_name_plural': 'Платежно-расчетные документы',
            },
        ),
        migrations.CreateModel(
            name='DocumentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Код товара')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('type_code', models.CharField(max_length=50, verbose_name='Код вида товара')),
                ('unit_code', models.CharField(max_length=10, verbose_name='Код единицы измерения')),
                ('excise', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Акциз')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('gtd_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер ГТД')),
                ('upd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents_сreating.documentupd', verbose_name='УПД')),
            ],
            options={
                'verbose_name': 'Товар документа',
                'verbose_name_plural': 'Товары документа',
            },
        ),
    ]
