# Generated by Django 5.2 on 2025-05-25 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bic', models.CharField(blank=True, max_length=9, null=True, verbose_name='БИК')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Наименование')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Место нахождения банка')),
                ('correspondent_account', models.CharField(blank=True, max_length=20, null=True, verbose_name='Корреспондентский счет')),
                ('current_account', models.CharField(blank=True, max_length=20, null=True, verbose_name='Текущий счет')),
            ],
            options={
                'verbose_name': 'Банк организации',
                'verbose_name_plural': 'Банк организации',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('short_name', models.CharField(max_length=10, verbose_name='Сокращенное наименование')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тип документа',
                'verbose_name_plural': 'Типы документов',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DocumentUTD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер счет-фактуры')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата счет-фактуры')),
                ('corr_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер исправления')),
                ('corr_date', models.DateField(blank=True, null=True, verbose_name='Дата исправления')),
                ('payment_document', models.CharField(blank=True, max_length=500, null=True, verbose_name='К платежно-расчетному документу')),
                ('is_advance', models.BooleanField(default=False, verbose_name='Авансовый платеж')),
                ('contract_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Идентификатор гос. контракта')),
                ('print_form', models.CharField(blank=True, max_length=255, null=True, verbose_name='Печатная форма')),
                ('transfer_basis', models.TextField(blank=True, null=True, verbose_name='Основание передачи/получения')),
                ('transport_info', models.TextField(blank=True, null=True, verbose_name='Данные о транспортировке и грузе')),
                ('transfer_position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность передатчика')),
                ('transfer_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО передатчика')),
                ('transfer_date', models.DateField(blank=True, null=True, verbose_name='Дата отгрузки')),
                ('transfer_additional_info', models.TextField(blank=True, null=True, verbose_name='Иные сведения об перемещении')),
                ('transfer_responsible_position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность ответственного за перемещение')),
                ('transfer_responsible_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО ответственного за перемещение')),
                ('receiver_position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность получателя')),
                ('receiver_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО получателя')),
                ('receipt_date', models.DateField(blank=True, null=True, verbose_name='Дата получения (приемки)')),
                ('receipt_additional_info', models.TextField(blank=True, null=True, verbose_name='Иные сведения о получении, приемке')),
                ('receipt_responsible_position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность ответственного за приемку')),
                ('receipt_responsible_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО ответственного за приемку')),
                ('is_stamp', models.BooleanField(default=False, verbose_name='Выводить печать')),
            ],
            options={
                'verbose_name': 'УПД',
                'verbose_name_plural': 'УПД',
            },
        ),
        migrations.CreateModel(
            name='InvoiceForPaymentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Количество')),
                ('unit', models.CharField(blank=True, max_length=100, null=True, verbose_name='Единица измерения')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('sum', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Товар документа оплаты',
                'verbose_name_plural': 'Товары документа оплаты',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование')),
                ('full_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Полное наименование')),
                ('conventional_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Условное наименование')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП')),
                ('is_ip', models.BooleanField(default=False, verbose_name='организация является ИП')),
                ('ogrn', models.CharField(blank=True, max_length=15, null=True, verbose_name='ОГРН/ОГРНИП')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('telephone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Телефон')),
                ('fax', models.CharField(blank=True, max_length=11, null=True, verbose_name='Организация Факс')),
                ('director_position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность руководителя')),
                ('director_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО руководителя')),
                ('accountant_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО бухгалтера')),
                ('stamp', models.ImageField(blank=True, null=True, upload_to='organization_stamps/', verbose_name='Печать')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='organization_signatures/', verbose_name='Подпись')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SellerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Статус продавца',
                'verbose_name_plural': 'Статусы продавцов',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Статусы',
                'verbose_name_plural': 'Статусы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StatusOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Статусы организаций',
                'verbose_name_plural': 'Статусы организаций',
                'ordering': ['organization'],
            },
        ),
        migrations.CreateModel(
            name='UTDItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код товара')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование')),
                ('type_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код вида товара')),
                ('unit_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Код единицы измерения')),
                ('excise', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Акциз')),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Количество')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна')),
                ('gtd_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер ГТД')),
            ],
            options={
                'verbose_name': 'Товар документа',
                'verbose_name_plural': 'Товары документа',
            },
        ),
        migrations.CreateModel(
            name='VatRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ставка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Ставка НДС',
                'verbose_name_plural': 'Ставки НДС',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DocumentInvoiceForPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('purpose_of_payment', models.CharField(blank=True, max_length=250, null=True, verbose_name='Цель платежа')),
                ('payment_for', models.CharField(blank=True, max_length=250, null=True, verbose_name='Платеж за')),
                ('agreement', models.CharField(blank=True, max_length=250, null=True, verbose_name='Договор')),
                ('printed_form', models.CharField(blank=True, max_length=100, null=True, verbose_name='Печатная форма')),
                ('discount', models.CharField(blank=True, max_length=6, null=True, verbose_name='Скидка')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Иные сведения')),
                ('is_stamp', models.BooleanField(default=False, verbose_name='Выводить печать')),
                ('buyer_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_bank_details', to='documents_сreating.bankdetails', verbose_name='Реквизиты банка контрагента')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents_сreating.currency', verbose_name='Валюта')),
                ('organization_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_bank_details', to='documents_сreating.bankdetails', verbose_name='Реквизиты банка организации')),
            ],
            options={
                'verbose_name': 'Счет на оплату',
                'verbose_name_plural': 'Счет на оплату',
            },
        ),
    ]
