# Generated by Django 5.2 on 2025-05-17 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bik', models.CharField(blank=True, max_length=9, null=True, verbose_name='БИК')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Наименование')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Место нахождения банка')),
                ('correspondent_account', models.CharField(blank=True, max_length=20, null=True, verbose_name='Корреспондентский счет')),
                ('current_account', models.CharField(blank=True, max_length=20, null=True, verbose_name='Текущий счет')),
            ],
            options={
                'verbose_name': 'Банк организации',
                'verbose_name_plural': 'Банк организации',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('short_name', models.CharField(max_length=10, verbose_name='Сокращенное наименование')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тип документа',
                'verbose_name_plural': 'Типы документов',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SellerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Статус продавца',
                'verbose_name_plural': 'Статусы продавцов',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VatRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ставка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Ставка НДС',
                'verbose_name_plural': 'Ставки НДС',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DocumentInvoiceForPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('purpose_of_payment', models.CharField(blank=True, max_length=250, null=True, verbose_name='Цель платежа')),
                ('payment_for', models.CharField(blank=True, max_length=250, null=True, verbose_name='Платеж за')),
                ('agreement', models.CharField(blank=True, max_length=250, null=True, verbose_name='Договор')),
                ('printed_form', models.CharField(blank=True, max_length=100, null=True, verbose_name='Печатная форма')),
                ('discount', models.CharField(blank=True, max_length=6, null=True, verbose_name='Скидка')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Иные сведения')),
                ('is_stamp', models.BooleanField(default=False, verbose_name='Выводить печать')),
                ('buyer_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_bank_details', to='documents_сreating.bankdetails', verbose_name='Реквизиты банка покупателя')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents_сreating.currency', verbose_name='Валюта')),
                ('organization_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_bank_details', to='documents_сreating.bankdetails', verbose_name='Реквизиты банка организации')),
                ('user', models.ForeignKey(help_text='Выбор пользователя', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Счет на оплату',
                'verbose_name_plural': 'Счет на оплату',
            },
        ),
        migrations.CreateModel(
            name='DocumentUPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер счет-фактуры')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='Дата счет-фактуры')),
                ('correction_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер исправления')),
                ('correction_date', models.DateField(blank=True, null=True, verbose_name='Дата исправления')),
                ('is_advance', models.BooleanField(default=False, verbose_name='Авансовый платеж')),
                ('seller_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование продавца')),
                ('seller_full_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Полное наименование продавца')),
                ('seller_inn', models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН продавца')),
                ('seller_kpp', models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП продавца')),
                ('seller_address', models.TextField(blank=True, null=True, verbose_name='Адрес продавца')),
                ('seller_director_position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность руководителя')),
                ('seller_director_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО руководителя')),
                ('seller_accountant_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО бухгалтера')),
                ('consignor_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование грузоотправителя')),
                ('consignor_inn', models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН грузоотправителя')),
                ('consignor_kpp', models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП грузоотправителя')),
                ('consignor_address', models.TextField(blank=True, null=True, verbose_name='Адрес грузоотправителя')),
                ('consignor_director_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО руководителя')),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование клиента')),
                ('customer_inn', models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН клиента')),
                ('customer_kpp', models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП клиента')),
                ('customer_address', models.TextField(blank=True, null=True, verbose_name='Адрес клиента')),
                ('customer_director_position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность руководителя')),
                ('customer_director_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО руководителя')),
                ('consignee_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование грузополучателя')),
                ('consignee_inn', models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН грузополучателя')),
                ('consignee_kpp', models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП грузополучателя')),
                ('consignee_address', models.TextField(blank=True, null=True, verbose_name='Адрес грузополучателя')),
                ('consignee_director_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО руководителя')),
                ('contract_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Идентификатор гос. контракта')),
                ('print_form', models.CharField(blank=True, max_length=255, null=True, verbose_name='Печатная форма')),
                ('transfer_basis', models.TextField(blank=True, null=True, verbose_name='Основание передачи/получения')),
                ('transport_info', models.TextField(blank=True, null=True, verbose_name='Данные о транспортировке и грузе')),
                ('transfer_position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность передатчика')),
                ('transfer_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО передатчика')),
                ('transfer_date', models.DateField(blank=True, null=True, verbose_name='Дата отгрузки')),
                ('transfer_additional_info', models.TextField(blank=True, null=True, verbose_name='Иные сведения об перемещении')),
                ('transfer_responsible_position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность ответственного за перемещение')),
                ('transfer_responsible_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО ответственного за перемещение')),
                ('receiver_position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность получателя')),
                ('receiver_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО получателя')),
                ('receipt_date', models.DateField(blank=True, null=True, verbose_name='Дата получения (приемки)')),
                ('receipt_additional_info', models.TextField(blank=True, null=True, verbose_name='Иные сведения о получении, приемке')),
                ('receipt_responsible_position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность ответственного за приемку')),
                ('receipt_responsible_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО ответственного за приемку')),
                ('document_seller_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование продавца-составителя')),
                ('document_seller_inn', models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН продавца-составителя')),
                ('document_seller_kpp', models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП продавца-составителя')),
                ('document_customer_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование покупателя-составителя')),
                ('document_customer_inn', models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН покупателя-составителя')),
                ('document_customer_kpp', models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП покупателя-составителя')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents_сreating.currency', verbose_name='Валюта')),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents_сreating.documenttype', verbose_name='Тип документа')),
                ('user', models.ForeignKey(help_text='Выбор пользователя', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('seller_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_status', to='documents_сreating.sellerstatus', verbose_name='Статус продавца')),
                ('vat_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents_сreating.vatrate', verbose_name='Ставка НДС')),
            ],
            options={
                'verbose_name': 'УПД',
                'verbose_name_plural': 'УПД',
            },
        ),
        migrations.CreateModel(
            name='InvoiceForPaymentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Количество')),
                ('unit', models.CharField(blank=True, max_length=100, null=True, verbose_name='Единица измерения')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('sum', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_docs', to='documents_сreating.documentinvoiceforpayment', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Товар документа оплаты',
                'verbose_name_plural': 'Товары документа оплаты',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование')),
                ('full_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Полное наименование')),
                ('conventional_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Условное наименование')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП')),
                ('is_ip', models.BooleanField(default=False, verbose_name='организация является ИП')),
                ('ogrn', models.CharField(blank=True, max_length=15, null=True, verbose_name='ОГРН/ОГРНИП')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('telephone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Телефон')),
                ('fax', models.CharField(blank=True, max_length=11, null=True, verbose_name='Организация Факс')),
                ('director_position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность руководителя')),
                ('director_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО руководителя')),
                ('accountant_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО бухгалтера')),
                ('stamp', models.ImageField(blank=True, null=True, upload_to='organization_stamps/', verbose_name='Печать')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='organization_signatures/', verbose_name='Подпись')),
                ('user', models.ForeignKey(help_text='Выбор пользователя', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='documentinvoiceforpayment',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='documents_сreating.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='documentinvoiceforpayment',
            name='consignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consignee', to='documents_сreating.organization', verbose_name='Грузополучатель'),
        ),
        migrations.AddField(
            model_name='documentinvoiceforpayment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='documents_сreating.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='documents_сreating.organization', verbose_name='Реквизиты банка'),
        ),
        migrations.CreateModel(
            name='PaymentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер документа')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата документа')),
                ('upd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_docs', to='documents_сreating.documentupd', verbose_name='УПД')),
            ],
            options={
                'verbose_name': 'Платежно-расчетный документ',
                'verbose_name_plural': 'Платежно-расчетные документы',
            },
        ),
        migrations.CreateModel(
            name='ShipmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование документа')),
                ('number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер документа')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата документа')),
                ('upd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_docs', to='documents_сreating.documentupd', verbose_name='УПД')),
            ],
            options={
                'verbose_name': 'Документ об отгрузке',
                'verbose_name_plural': 'Документы об отгрузке',
            },
        ),
        migrations.CreateModel(
            name='StatusOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_org', to='documents_сreating.organization', verbose_name='Организация')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_status', to='documents_сreating.status', verbose_name='Статус')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UPDItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код товара')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование')),
                ('type_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код вида товара')),
                ('unit_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Код единицы измерения')),
                ('excise', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Акциз')),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Количество')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна')),
                ('gtd_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер ГТД')),
                ('upd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_docs', to='documents_сreating.documentupd', verbose_name='УПД')),
            ],
            options={
                'verbose_name': 'Товар документа',
                'verbose_name_plural': 'Товары документа',
            },
        ),
        migrations.AddField(
            model_name='documentinvoiceforpayment',
            name='vat_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents_сreating.vatrate', verbose_name='Ставка НДС'),
        ),
    ]
