# Generated by Django 5.2 on 2025-05-17 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents_сreating', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['name'], 'verbose_name': 'Статусы', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterModelOptions(
            name='statusorganization',
            options={'ordering': ['organization'], 'verbose_name': 'Статусы организаций', 'verbose_name_plural': 'Статусы организаций'},
        ),
    ]
