# Generated by Django 5.2 on 2025-05-13 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents_сreating', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentinvoiceforpayment',
            name='user',
            field=models.ForeignKey(help_text='Выбор пользователя', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='documentupd',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents_сreating.currency', verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='documentupd',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents_сreating.documenttype', verbose_name='Тип документа'),
        ),
        migrations.AddField(
            model_name='documentupd',
            name='user',
            field=models.ForeignKey(help_text='Выбор пользователя', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='invoiceforpaymentitem',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_docs', to='documents_сreating.documentinvoiceforpayment', verbose_name='Документ'),
        ),
        migrations.AddField(
            model_name='organization',
            name='user',
            field=models.ForeignKey(help_text='Выбор пользователя', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='paymentdocument',
            name='upd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_docs', to='documents_сreating.documentupd', verbose_name='УПД'),
        ),
        migrations.AddField(
            model_name='documentupd',
            name='seller_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_status', to='documents_сreating.sellerstatus', verbose_name='Статус продавца'),
        ),
        migrations.AddField(
            model_name='shipmentdocument',
            name='upd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_docs', to='documents_сreating.documentupd', verbose_name='УПД'),
        ),
        migrations.AddField(
            model_name='upditem',
            name='upd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_docs', to='documents_сreating.documentupd', verbose_name='УПД'),
        ),
        migrations.AddField(
            model_name='documentupd',
            name='vat_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents_сreating.vatrate', verbose_name='Ставка НДС'),
        ),
        migrations.AddField(
            model_name='documentinvoiceforpayment',
            name='vat_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents_сreating.vatrate', verbose_name='Ставка НДС'),
        ),
    ]
