# Generated by Django 5.2 on 2025-04-29 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents_сreating', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EconomicObject',
        ),
    ]
