# Generated by Django 5.2 on 2025-05-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_сreating', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utditem',
            name='sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма'),
        ),
    ]
