# Generated by Django 5.2 on 2025-04-29 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_сreating', '0002_delete_economicobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentupd',
            name='consignee_address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес грузополучателя'),
        ),
        migrations.AlterField(
            model_name='documentupd',
            name='consignee_director_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО руководителя'),
        ),
        migrations.AlterField(
            model_name='documentupd',
            name='consignee_inn',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН грузополучателя'),
        ),
        migrations.AlterField(
            model_name='documentupd',
            name='consignee_kpp',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП грузополучателя'),
        ),
        migrations.AlterField(
            model_name='documentupd',
            name='consignee_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование грузополучателя'),
        ),
        migrations.AlterField(
            model_name='documentupd',
            name='consignor_address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес грузоотправителя'),
        ),
        migrations.AlterField(
            model_name='documentupd',
            name='consignor_director_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО руководителя'),
        ),
        migrations.AlterField(
            model_name='documentupd',
            name='consignor_inn',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН грузоотправителя'),
        ),
        migrations.AlterField(
            model_name='documentupd',
            name='consignor_kpp',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП грузоотправителя'),
        ),
        migrations.AlterField(
            model_name='documentupd',
            name='consignor_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование грузоотправителя'),
        ),
        migrations.AlterField(
            model_name='documentupd',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents_сreating.currency', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='documentupd',
            name='customer_address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес клиента'),
        ),
        migrations.AlterField(
            model_name='documentupd',
            name='customer_director_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО руководителя'),
        ),
        migrations.AlterField(
            model_name='documentupd',
            name='customer_director_position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность руководителя'),
        ),
        migrations.AlterField(
            model_name='documentupd',
            name='customer_inn',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН клиента'),
        ),
        migrations.AlterField(
            model_name='documentupd',
            name='customer_kpp',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП клиента'),
        ),
        migrations.AlterField(
            model_name='documentupd',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование клиента'),
        ),
        migrations.AlterField(
            model_name='documentupd',
            name='document_customer_inn',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН покупателя-составителя'),
        ),
        migrations.AlterField(
            model_name='documentupd',
            name='document_customer_kpp',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП покупателя-составителя'),
        ),
        migrations.AlterField(
            model_name='documentupd',
            name='document_customer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование покупателя-составителя'),
        ),
        migrations.AlterField(
            model_name='documentupd',
            name='document_seller_inn',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН продавца-составителя'),
        ),
        migrations.AlterField(
            model_name='documentupd',
            name='document_seller_kpp',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП продавца-составителя'),
        ),
        migrations.AlterField(
            model_name='documentupd',
            name='document_seller_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование продавца-составителя'),
        ),
        migrations.AlterField(
            model_name='documentupd',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents_сreating.documenttype', verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='documentupd',
            name='invoice_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата счет-фактуры'),
        ),
        migrations.AlterField(
            model_name='documentupd',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер счет-фактуры'),
        ),
        migrations.AlterField(
            model_name='documentupd',
            name='print_form',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Печатная форма'),
        ),
        migrations.AlterField(
            model_name='documentupd',
            name='receipt_additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='Иные сведения о получении, приемке'),
        ),
        migrations.AlterField(
            model_name='documentupd',
            name='receipt_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата получения (приемки)'),
        ),
        migrations.AlterField(
            model_name='documentupd',
            name='receipt_responsible_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО ответственного за приемку'),
        ),
        migrations.AlterField(
            model_name='documentupd',
            name='receipt_responsible_position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность ответственного за приемку'),
        ),
        migrations.AlterField(
            model_name='documentupd',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО получателя'),
        ),
        migrations.AlterField(
            model_name='documentupd',
            name='receiver_position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность получателя'),
        ),
        migrations.AlterField(
            model_name='documentupd',
            name='seller_accountant_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО бухгалтера'),
        ),
        migrations.AlterField(
            model_name='documentupd',
            name='seller_address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес продавца'),
        ),
        migrations.AlterField(
            model_name='documentupd',
            name='seller_director_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО руководителя'),
        ),
        migrations.AlterField(
            model_name='documentupd',
            name='seller_director_position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность руководителя'),
        ),
        migrations.AlterField(
            model_name='documentupd',
            name='seller_full_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Полное наименование продавца'),
        ),
        migrations.AlterField(
            model_name='documentupd',
            name='seller_inn',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН продавца'),
        ),
        migrations.AlterField(
            model_name='documentupd',
            name='seller_kpp',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП продавца'),
        ),
        migrations.AlterField(
            model_name='documentupd',
            name='seller_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование продавца'),
        ),
        migrations.AlterField(
            model_name='documentupd',
            name='seller_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_status', to='documents_сreating.sellerstatus', verbose_name='Статус продавца'),
        ),
        migrations.AlterField(
            model_name='documentupd',
            name='transfer_additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='Иные сведения об перемещении'),
        ),
        migrations.AlterField(
            model_name='documentupd',
            name='transfer_basis',
            field=models.TextField(blank=True, null=True, verbose_name='Основание передачи/получения'),
        ),
        migrations.AlterField(
            model_name='documentupd',
            name='transfer_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отгрузки'),
        ),
        migrations.AlterField(
            model_name='documentupd',
            name='transfer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО передатчика'),
        ),
        migrations.AlterField(
            model_name='documentupd',
            name='transfer_position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность передатчика'),
        ),
        migrations.AlterField(
            model_name='documentupd',
            name='transfer_responsible_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО ответственного за перемещение'),
        ),
        migrations.AlterField(
            model_name='documentupd',
            name='transfer_responsible_position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность ответственного за перемещение'),
        ),
        migrations.AlterField(
            model_name='documentupd',
            name='transport_info',
            field=models.TextField(blank=True, null=True, verbose_name='Данные о транспортировке и грузе'),
        ),
        migrations.AlterField(
            model_name='documentupd',
            name='vat_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents_сreating.vatrate', verbose_name='Ставка НДС'),
        ),
    ]
