# Generated by Django 5.2 on 2025-05-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_сreating', '0003_utditem_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utditem',
            name='unit_code',
        ),
        migrations.AddField(
            model_name='documentutd',
            name='shipping_document',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Документ об отгрузке'),
        ),
        migrations.AddField(
            model_name='utditem',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Единица измерения'),
        ),
    ]
