# Generated by Django 5.2 on 2025-04-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_сreating', '0003_alter_documentupd_consignee_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentitem',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='documentitem',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код товара'),
        ),
        migrations.AlterField(
            model_name='documentitem',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='documentitem',
            name='excise',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Акциз'),
        ),
        migrations.AlterField(
            model_name='documentitem',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='documentitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='documentitem',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='documentitem',
            name='type_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код вида товара'),
        ),
        migrations.AlterField(
            model_name='documentitem',
            name='unit_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Код единицы измерения'),
        ),
        migrations.AlterField(
            model_name='paymentdocument',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата документа'),
        ),
        migrations.AlterField(
            model_name='paymentdocument',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер документа'),
        ),
        migrations.AlterField(
            model_name='shipmentdocument',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата документа'),
        ),
        migrations.AlterField(
            model_name='shipmentdocument',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование документа'),
        ),
        migrations.AlterField(
            model_name='shipmentdocument',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер документа'),
        ),
    ]
