# Generated by Django 5.2 on 2025-05-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_сreating', '0004_remove_utditem_unit_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentutd',
            name='transfer_basis',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Основание передачи/получения'),
        ),
        migrations.AlterField(
            model_name='documentutd',
            name='transport_info',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Данные о транспортировке и грузе'),
        ),
    ]
