# Generated by Django 5.2 on 2025-04-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_сreating', '0004_alter_documentitem_amount_alter_documentitem_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='accountant_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО бухгалтера'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='director_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО руководителя'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='director_position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность руководителя'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='full_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Полное наименование'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='kpp',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='ogrn',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='okpo',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Код ОКПО'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='okved',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Код ОКВЭД'),
        ),
    ]
