# Generated by Django 5.2 on 2025-05-11 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_сreating', '0005_alter_organization_accountant_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentInvoiceForPayment',
            fields=[
                ('basedocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents_сreating.basedocument')),
                ('organization_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Организация Наименование')),
                ('organization_inn', models.CharField(blank=True, max_length=12, null=True, verbose_name='Организация ИНН')),
                ('organization_kpp', models.CharField(blank=True, max_length=9, null=True, verbose_name='Организация КПП')),
                ('organization_is_IP', models.BooleanField(default=False, verbose_name='организация является ИП')),
                ('organization_main_state_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Организация Основной государственный регистрационный номер')),
                ('organization_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Организация Адрес')),
                ('organization_telephone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Организация Телефон')),
                ('organization_fax', models.CharField(blank=True, max_length=11, null=True, verbose_name='Организация Факс')),
                ('organization_director_position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Организация Должность директора')),
                ('organization_director_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Организация Директор')),
                ('organization_accountant_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Организация Бухгалтер')),
                ('organization_conventional_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Организация условное наименование')),
                ('organization_bik', models.CharField(blank=True, max_length=9, null=True, verbose_name='Организация БИК')),
                ('organization_bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Организация Наименование банка')),
                ('organization_place_of_registration', models.CharField(blank=True, max_length=100, null=True, verbose_name='Организация Место нахождения')),
                ('organization_correspondent_account', models.CharField(blank=True, max_length=20, null=True, verbose_name='Организация Корреспондентский счет')),
                ('organization_current_account', models.CharField(blank=True, max_length=20, null=True, verbose_name='Организация Текущий счет')),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Покупатель Наименование')),
                ('customer_inn', models.CharField(blank=True, max_length=12, null=True, verbose_name='Покупатель ИНН')),
                ('customer_kpp', models.CharField(blank=True, max_length=9, null=True, verbose_name='Покупатель КПП')),
                ('customer_is_IP', models.BooleanField(default=False, verbose_name='Покупатель является ИП')),
                ('customer_main_state_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Покупатель Основной государственный регистрационный номер')),
                ('customer_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Покупатель Адрес')),
                ('customer_telephone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Покупатель Телефон')),
                ('customer_conventional_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Покупатель условное наименование')),
                ('customer_bik', models.CharField(blank=True, max_length=9, null=True, verbose_name='Покупатель БИК')),
                ('customer_bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Покупатель Наименование банка')),
                ('customer_place_of_registration', models.CharField(blank=True, max_length=100, null=True, verbose_name='Покупатель Место нахождения')),
                ('customer_correspondent_account', models.CharField(blank=True, max_length=20, null=True, verbose_name='Покупатель Корреспондентский счет')),
                ('customer_current_account', models.CharField(blank=True, max_length=20, null=True, verbose_name='Покупатель Текущий счет')),
                ('consignee_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Грузополучатель Наименование')),
                ('consignee_inn', models.CharField(blank=True, max_length=12, null=True, verbose_name='Грузополучатель ИНН')),
                ('consignee_kpp', models.CharField(blank=True, max_length=9, null=True, verbose_name='Грузополучатель КПП')),
                ('consignee_is_IP', models.BooleanField(default=False, verbose_name='Грузополучатель является ИП')),
                ('consignee_main_state_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Грузополучатель Основной государственный регистрационный номер')),
                ('consignee_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Грузополучатель Адрес')),
                ('consignee_telephone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Грузополучатель Телефон')),
                ('purpose_of_payment', models.CharField(blank=True, max_length=100, null=True, verbose_name='Цель платежа')),
                ('payment_for', models.CharField(blank=True, max_length=100, null=True, verbose_name='Платеж за')),
                ('agreement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Договор')),
                ('printed_form', models.CharField(blank=True, max_length=100, null=True, verbose_name='Печатная форма')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Скидка')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents_сreating.currency', verbose_name='Валюта')),
                ('vat_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents_сreating.vatrate', verbose_name='Ставка НДС')),
            ],
            options={
                'abstract': False,
            },
            bases=('documents_сreating.basedocument',),
        ),
        migrations.CreateModel(
            name='InvoiceForPaymentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Количество')),
                ('unit', models.CharField(blank=True, max_length=100, null=True, verbose_name='Единица измерения')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('sum', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents_сreating.documentinvoiceforpayment', verbose_name='Документ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UPDItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код товара')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование')),
                ('type_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код вида товара')),
                ('unit_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Код единицы измерения')),
                ('excise', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Акциз')),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Количество')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна')),
                ('gtd_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер ГТД')),
                ('upd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_docs', to='documents_сreating.documentupd', verbose_name='УПД')),
            ],
            options={
                'verbose_name': 'Товар документа',
                'verbose_name_plural': 'Товары документа',
            },
        ),
        migrations.DeleteModel(
            name='DocumentItem',
        ),
    ]
