# Generated by Django 5.2 on 2025-05-25 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents_сreating', '0005_alter_documentutd_transfer_basis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utditem',
            name='amount',
        ),
    ]
