# Generated by Django 5.2 on 2025-05-12 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_сreating', '0006_documentinvoiceforpayment_invoiceforpaymentitem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentinvoiceforpayment',
            options={'verbose_name': 'Счет на оплату', 'verbose_name_plural': 'Счет на оплату'},
        ),
        migrations.AlterModelOptions(
            name='invoiceforpaymentitem',
            options={'verbose_name': 'Товар документа оплаты', 'verbose_name_plural': 'Товары документа оплаты'},
        ),
        migrations.RemoveField(
            model_name='documentinvoiceforpayment',
            name='organization_place_of_registration',
        ),
        migrations.AddField(
            model_name='documentinvoiceforpayment',
            name='organization_bank_place_of_registration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Организация Место нахождения банка'),
        ),
    ]
