# Generated by Django 5.2 on 2025-05-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_сreating', '0007_alter_documentinvoiceforpayment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentinvoiceforpayment',
            name='invoice_for_payment_data',
            field=models.DateField(blank=True, null=True, verbose_name='Дата счет на оплату'),
        ),
        migrations.AddField(
            model_name='documentinvoiceforpayment',
            name='invoice_for_payment_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер счет на оплату'),
        ),
    ]
