# Generated by Django 5.2 on 2025-05-12 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_сreating', '0008_documentinvoiceforpayment_invoice_for_payment_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceforpaymentitem',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_docs', to='documents_сreating.documentinvoiceforpayment', verbose_name='Документ'),
        ),
    ]
