# Generated by Django 5.2 on 2025-05-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_сreating', '0009_alter_invoiceforpaymentitem_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentupd',
            name='basedocument_ptr',
        ),
        migrations.RemoveField(
            model_name='documentinvoiceforpayment',
            name='basedocument_ptr',
        ),
        migrations.AddField(
            model_name='documentinvoiceforpayment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='documentupd',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='BaseDocument',
        ),
    ]
